require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - 'lib/alexandria/default_preferences.rb'
    - 'pkg/**/*'
  TargetRubyVersion: 2.4

# Dot at end of line makes it clearer that the line is not done
Layout/DotPosition:
  EnforcedStyle: trailing

# Multi-line assignment should be simply indented. Aligning them makes it even
# harder to keep a sane line length.
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

# Multi-line method calls should be simply indented. Aligning them makes it
# even harder to keep a sane line length.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Make syntax for empty and filled blocks consistent
Layout/SpaceBeforeBlockBraces:
  EnforcedStyleForEmptyBraces: space

Layout/AlignHash:
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: table

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

# Blocks in specs can be any size
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Be lenient with line length
Metrics/LineLength:
  Max: 110

Naming/AccessorMethodName:
  Enabled: false

# Avoid one-letter exception variable name
Naming/RescuedExceptionsVariableName:
  PreferredName: ex

# Allow multi-line blocks of all sorts
Style/BlockDelimiters:
  Enabled: false

# Allow and/or for control flow only
Style/AndOr:
  EnforcedStyle: conditionals

# Require at least two dependent lines before suggesting a guard clause
Style/GuardClause:
  MinBodyLength: 2

# Not all objects that handle #== 0 also handle #zero?
Style/NumericPredicate:
  Enabled: false

# Sometimes an if statement just looks better than next with a guard clause
Style/Next:
  Enabled: false

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# Allow explicit return with multiple return values
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

# I like to have symbols always look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets

# Accessors are only trivial if they match the ivar name.
Style/TrivialAccessors:
  ExactNameMatch: true

# Allow semantic choice of trailing comma
Style/TrailingCommaInArrayLiteral:
  Enabled: false

# Alexandria uses regular arrays
Style/WordArray:
  Enabled: false

# Not all objects that handle #length also handle #empty?
Style/ZeroLengthPredicate:
  Enabled: false

inherit_from: .rubocop_todo.yml
