AllCops:
  Exclude:
    - 'pkg/**/*'

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

# Allow multi-line blocks of all sorts
Style/BlockDelimiters:
  Enabled: false

# Dot at end of line makes it clearer that the line is not done
Style/DotPosition:
  EnforcedStyle: trailing

# Require lines to fit in pull requests.
# This config is commented out temporarily to allow .rubocop_todo.yml to
# configure this cop.
#Style/LineLength:
  #Max: 92

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

# Allow explicit return with multiple return values
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FirstParameterIndentation:
  EnforcedStyle: consistent

# Require at least two dependent lines before suggesting a guard clause
Style/GuardClause:
  MinBodyLength: 2

# Don't use if or unless as modifier if the line gets too long
Style/IfUnlessModifier:
  MaxLineLength: 60

# Visually mark multiline operations by indenting
Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/TrivialAccessors:
  ExactNameMatch: true

Style/SingleLineBlockParams:
  Enabled: false

# Sometimes an if statement just looks better than next with a guard clause
Style/Next:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

# Support use of and and or for control flow.
Style/AndOr:
  Enabled: false

# Allow semantic choice of trailing comma
Style/TrailingCommaInLiteral:
  Enabled: false

# Alexandria uses regular arrays
Style/WordArray:
  Enabled: false

inherit_from: .rubocop_todo.yml
