AllCops:
  Exclude:
    - 'pkg/**/*'

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

# Require lines to fit in pull requests.
# This config is commented out temporarily to allow .rubocop_todo.yml to
# configure this cop.
#Metrics/LineLength:
  #Max: 92

Style/AccessorMethodName:
  Enabled: false

# Allow multi-line blocks of all sorts
Style/BlockDelimiters:
  Enabled: false

# Allow and/or for control flow only
Style/AndOr:
  Enabled: conditionals

# Dot at end of line makes it clearer that the line is not done
Style/DotPosition:
  EnforcedStyle: trailing

# Require at least two dependent lines before suggesting a guard clause
Style/GuardClause:
  MinBodyLength: 2

# Don't use if or unless as modifier if the line gets too long
Style/IfUnlessModifier:
  MaxLineLength: 60

# Multi-line assignment should be simply indented. Aligning them makes it even
# harder to keep a sane line length.
Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

# Multi-line method calls should be simply indented. Aligning them makes it
# even harder to keep a sane line length.
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Sometimes an if statement just looks better than next with a guard clause
Style/Next:
  Enabled: false

# Allow explicit return with multiple return values
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

# Accessors are only trivial if they match the ivar name.
Style/TrivialAccessors:
  ExactNameMatch: true

# Allow semantic choice of trailing comma
Style/TrailingCommaInLiteral:
  Enabled: false

# Alexandria uses regular arrays
Style/WordArray:
  Enabled: false

inherit_from: .rubocop_todo.yml
