language: ruby

before_install:
  - sudo apt-get update
  - sudo apt-get install libgtk-3-dev
  - sudo apt-get install libgstreamer1.0-dev
  - sudo apt-get install libgoocanvas-2.0-dev
  - sudo apt-get install libyaz-dev
  - sudo apt-get install intltool
  - sudo apt-get install gconf2
  - sudo apt-get install at-spi2-core
  - sudo apt-get install gstreamer1.0-plugins-good
  - sudo apt-get install pulseaudio

script: "xvfb-run bundle exec rake"

rvm:
  - 2.6

branches:
  only:
    - master
